### ISSUE TITLE
Create the Flag

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#14]
Create a new class called Flag that contains the following things:

- [x] An x & y position variable - assigned in the constructor

- [x] A draw function that draws the flag sprite at the position of the flag

**Comment by rijkvp** [comment]
@Dreojs-NL please note that you're not creating a class in commit fc3fc182de9b2b48da07e0bbea43486e6d7b7310. You probably don't even know what a class is 😉 So we will help you tonight.

**Comment by ghost** [comment]
Ok thx

Op do 10 sep. 2020 18:01 schreef Rijk van Putten <notifications@github.com>:
