### ISSUE TITLE
Find a maze generation algorithm

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#17]
Search in the internet to find a maze generation algorithm that we can use in our tank battalion game.

**Comment by robkruger** [comment]
Using a maze generation algorithm like Pac-Man looks the closest to TB MSX, but we could use a 'normal' algorithm too.
The maps in the original game are probably manually created, so if we do that too that will look the best.

My suggestion is to just manually create the map(s).

**Comment by rijkvp** [comment]
I agee! I wasn't sure about this. Loading some text files is the easiest for now I think
