### ISSUE TITLE
Create state system

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#37]
Currently we handle everything in the setup() and draw() functions. As the game gets more complex I think we need some kind of state system / state machine to handle the different kinds of states.
I have coded a state system before with a state class: [State.js](https://github.com/Rijk-van-Putten/P5_Game-Assignment/blob/master/game/js/State.js) and a state machine class: [StateManager.js](https://github.com/Rijk-van-Putten/P5_Game-Assignment/blob/master/game/js/StateManager.js). Maybe we can use something similar.

**Comment by rijkvp** [comment]
@richelbilderbeek would you like to check this out?

**Comment by richelbilderbeek** [comment]
Brilliant! This is exactly what a state design pattern is made for :+1:
