### ISSUE TITLE
Determine size of the screen

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2020#4]
Use this sprite's size as the size used by the game:

![](https://raw.githubusercontent.com/djog/djog_unos_2020/master/data/Background.png)

**Comment by robkruger** [comment]
256x192. I suggest we make it larger though, as this is really small.

**Comment by rijkvp** [comment]
I resized the image to `1600 x 900` a modern aspect ratio.

**Comment by rijkvp** [comment]
The game area (in the green border) is now: X: 233 & Y: 32, Width: 836, Height: 836  `
