### ISSUE TITLE
Create a rainbow tank

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2020#43]
Sometimes, a random rainbow tank might spawn in the game. I don't know the exact odds, but they are rare. 

- [x] Add a new boolean in the Enemy class called "rainbow"
- [x] Also add this to the constructor
- [x] In the spawn_enemies() method, add the small possibility of a tank to become a rainbow tank (like 1/20)
- [x] In the draw() method in the Enemy class, change the color of the enemies if they are a rainbow tank (it looks like you can do this with the [tint method](https://www.processing.org/reference/tint_.html))

This is it for now, we will later add the feature were the player gets a superpower if they destroy the rainbow tank.

**Comment by rijkvp** [comment]
Done!
