### ISSUE TITLE
Add health system 

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#45]
Currently the player & the enemies can't die yet. 
Add a health system so that the tanks can take damage and eventually die:

- [x] Add a integer variable called `health` on the player/enemy classes
- [x] Add a boolean variable called `is_dead` to the player/enemy classes
- [ ] Add a method  `take_damage(int damage)` to the player/enemy classes. The damage should be subtracted from the tanks health. If the health is equal to or below zero `is_dead` should be set to true
- [ ] Remove enemies form the ArrayList if they are dead
- [ ] Test out the code by subtracting a random ammout of health from the enemies every frame (delta_time * (some random))

**Comment by rijkvp** [comment]
@richelbilderbeek can we use a design pattern here? The code will likely get messy because of this issue and shell collision.

**Comment by richelbilderbeek** [comment]
> can we use a design pattern here?

@Rijk-van-Putten, AFAICS, there is design pattern that fits in naturally here. I feel a bunch of functions are all that is needed to do the trick. Or did I overlook a pattern?

**Comment by rijkvp** [comment]
Maybe not particularly a design pattern but instead inheritance or polymorphism. For example a parent tank class with the collision & health stuff which the player and enemy can inherit. I don't want to make it too complex but implementing all the health stuff two times sounds like it's going to be really messy.

**Comment by richelbilderbeek** [comment]
I agree that the task will be complex. 

I do predict that using inheritance/polymorphism here is a bad fit: it does not *sound* natural to have a 'parent tank'. Maybe naming it a `Sprite` class is a more natural fit (of types `Player` and `Enemy`), but still I am unconvinced.

We both agree that function duplication is a bad idea. A member function for all types of sprites (say `get_sprite_rect`) and a `Rectangle` class to work on seems like a superior way to me.

Would the team be more experienced, I would encourage you to try it out: let's get the newbies up to speed first :+1:

**Comment by rijkvp** [comment]
Done & not really needed anymore
