### ISSUE TITLE
Create the additional layouts

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2020#46]
As you can see [here](https://strategywiki.org/wiki/Tank_Battalion/Walkthrough), there are 8 different layouts the map can have.
Currently we only have 1 layout.

- [x] Create the second layout
- [ ] Create the third layout
- [ ] Create the fourth layout
- [ ] Create the fifth layout
- [ ] Create the sixth layout
- [ ] Create the seventh layout
- [ ] Create the eighth layout

To create a new layout, create a new .ini file called layout-x.ini
You can look in the file layout-1.ini how to create one.

- `0` means that there is no brick in that position
- `1` means that there is a topleft-brick section in that position 
- `2` means that there is a topright-brick section in that position 
- `3` means that there is a bottomleft-brick section in that position
- `4` means that there is a bottomright-brick section in that position

**Comment by rijkvp** [comment]
Someone will take this furder
