### ISSUE TITLE
Create a basic round system

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2020#47]
~~As you can see [here](https://strategywiki.org/wiki/Tank_Battalion/Walkthrough), there are different layouts for each round.~~
~~Once #46 is done, you can create a system to load the different layout for each round.~~
Add placeholders

- [x] In the constructor of the `grid` class, add a new string variable called `layout_file`, which holds the name of the layout file to load.
- [x] Create a new method called `on_new_round()` in the `game_state` file
- [x] Add a switch statement, which returns the layout file name for each round (In [this](https://strategywiki.org/wiki/Tank_Battalion/Walkthrough) link, it shows which layout to use for each round)
- [x] Initialize the grid again (`grid = new Grid("layout-x");`), reposition the player to its starting position again and empty the enemy ArrayList
- [x] Spawn enemies left according to a variable
- [x] Add placeholders for the layouts

I think this should do the job, but maybe @Rijk-van-Putten has a better or cleaner idea of how to do this. - Yes I have (partly)

**Comment by rijkvp** [comment]
@robkruger Note that the function also needs to be called for the first round. Probably this requires moving some things arround in the on_start. 

In addition: Don't forget the round variable: the switch statement can be simplified

**Comment by rijkvp** [comment]
I'll do this
