### ISSUE TITLE
Enemies should die if they are hit

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2020#56]
If an enemy get's hit **by a player's shell**, it should die. 

~~- [ ] Create a variable (for example  `boolean shot_by_player`) to know the difference between a shell shot by a player and one by an enemy~~

- [ ] Implement collision detection between a shell ~~(with `shot_by_player = true`)~~ and an enemy
- [ ] Set `is_dead` to true

~~- [ ] Remove the enemy (Don't forget it's collider) from the game~~

**Comment by rijkvp** [comment]
Please don't fix this yet, see #55

**Comment by rijkvp** [comment]
> If an enemy get's hit **by a player's shell**, it should die.
> 
> * [ ]  Create a variable (for example  `boolean shot_by_player`) to know the difference between a shell shot by a player and one by an enemy
> * [ ]  Implement collision detection between a shell (with `shot_by_player = true`) and an enemy
> * [ ]  Remove the enemy (Don't forget it's collider) from the game

Please note that the enemies already have a `is_dead` and they will be automatically removed. 
Additionally this depends on #60 which I will fix ASAP so you can continue working.
