### ISSUE TITLE
Add a proper menu interface 

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#58]
Add a proper menu screen instead of the boring placeholder right now.

**Comment by richelbilderbeek** [comment]
I would personally enjoy a very similar menu screen as the original:

![menu_screen](https://user-images.githubusercontent.com/2098230/95422333-68286700-093f-11eb-8e74-af87151696dd.jpeg)


Just add some sneaky modifications that will go unnoticed to the unaware. Maybe the team should be called `Namc0` :grin:
