### ISSUE TITLE
There are no sound files

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#63]
@richelbilderbeek  We need the original game sounds. @richelbilderbeek promised to do this before next week.

**Comment by richelbilderbeek** [comment]
I've asked the mighty Dirk (an Appingedam volunteer). Also, I would not mind someone else to do this in the holiday :+1:

**Comment by richelbilderbeek** [comment]
I've added `start_music.ogg`, `start_music.wav` and `start_music.mp3` in `assets/sound` :+1:

**Comment by rijkvp** [comment]
Done
