### ISSUE TITLE
Add score pop ups when an enemy is killed.

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2020#65]
According to [the wiki](https://strategywiki.org/wiki/Tank_Battalion) the score you gain from killing an enemy is random between 30 and 1600 (Although it looks like it's only round numbers, maybe the person doing this issue could further investigate how exactly the score is determined?)

This score is currently added to the total score but there should be a short pop up showing how much points you gained in the place where the enemy got destroyed. Add this

**Comment by richelbilderbeek** [comment]
I've found out how the score is determined from [the service manual](https://www.arcade-museum.com/manuals-videogames/N/Namco%20Tank%20Battalion%20Service%20Manual.pdf):

![Screenshot from 2020-10-09 10-13-13](https://user-images.githubusercontent.com/2098230/95559518-30d9b900-0a18-11eb-8ef2-4393a3de72e8.png)

**Comment by rijkvp** [comment]
And of course, there should be explosions! 💣 💥 💣 💥💣 💥💣 💥
But that's for [another issue](https://github.com/djog/djog_unos_2020/issues/11).

**Comment by rijkvp** [comment]
Done!
