### ISSUE TITLE
Draw the score

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2020#7]
In the screenshot below, the player has a score:

![](https://raw.githubusercontent.com/djog/djog_unos_2020/master/data/Background.png)

 * Add a variable to keep track of the score. Call it `score`
 * Show the score
 * Use `;` to decrease the score in steps of 1, if there the score is above 1
 * Use `'` to increase the score, if the score is less then 999,999 (i.e. 1 million minus 1)

**Comment by rijkvp** [comment]
You can do this now. Don't forget to pull!

**Comment by rijkvp** [comment]
Done & merged

**Comment by AramPetiet** [comment]
I noticed that the score doesn't actually go up. Maybe I'm wrong but if I'm not, you need to add this feature for this issue to be done

**Comment by rijkvp** [comment]
@AramPetiet thanks for noticing! Me and @martje127 forgot about that. That was just for debugging purpusses. We tried out assigning different values and it worked. We will create another issue when actually implementing the score.
