### ISSUE TITLE
Draw the round

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2020#8]
In the screenshot below, the player is at a certain level, called the `round`:

![](https://raw.githubusercontent.com/djog/djog_unos_2020/master/data/Background.png)

 * Add a variable to keep track of the round. Call it `round`
 * Show the round
 * Use `.` to decrease the round in steps of 1, if the round is above 1
 * Use `/` to increase the round, if the round is less then 99

**Comment by rijkvp** [comment]
You can do this now. Don't forget to pull!
