### ISSUE TITLE
Publish the game

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#89]
Depends on all Release milestone issues!
- [x] Fix the last few bugs
- [x] Export for Windows 64bit
- [x] Ex[prt for Linux
- [ ] Upload to itch.io (discuss)

**Comment by richelbilderbeek** [comment]
I suggest we send an email to Konami before publishing on Itch. I feel that is more polite and can save a lot of potential trouble. I did the same for City of Thieves, where I contacted the publisher. Sure, I volunteer to do so this Thursday :+1:

**Comment by rijkvp** [comment]
> I suggest we send an email to Konami before publishing on Itch. I feel that is more polite and can save a lot of potential trouble. I did the same for City of Thieves, where I contacted the publisher. Sure, I volunteer to do so this Thursday 👍

👍

**Comment by richelbilderbeek** [comment]
Sent to Konami at [this Contact Form](https://www.konami.com/gaming/corporate/Home/Contact.aspx):

> Dear Konami,
>
> I would like to inquire about possible problems with copyright.
>
> A team of programmers and I have created a clone of the Konami 1984 game 'Tank Battalion'. It was my favorite game as a kid! We use exactly the same graphics and sound, using an open source license and we fully acknowledge that the game is a clone of a Konami game. We never intend to monetize this game, but we would enjoy to put it on Twitch.
>
> Can we publish the game as such, or will we need to change the graphics and sound?
>
> Thanks for making great games and letting me know if we can proudly publish this tribute to one of my favorite games!
>
> Cheers, Richel Bilderbeek

**Comment by rijkvp** [comment]
@richelbilderbeek Nice!  But note that I changed some sounds (and graphics a bit). And why Twich? Didn't you mean Itch.io?

**Comment by richelbilderbeek** [comment]
From Konami (literal copy-paste, layout theirs):

> Konami Gaming, Inc. Website Contact Form Submission
> 12 December 2020 15:36 12 KB
> From: info@konamigaming.com
> To: [richel]


Hello,                                                                                                        Thank you for your inquiry. Your form created on 12/12/2020 has been submitted successfully. | Hello,                                                                                                        Thank you for your inquiry. Your form created on 12/12/2020 has been submitted successfully. |  
-- | -- | --
Hello,                                                                                                        Thank you for your inquiry. Your form created on 12/12/2020 has been submitted successfully. |  
A KONAMI customer service representative will review your request. |   | A KONAMI customer service representative will review your request. |  
  | A KONAMI customer service representative will review your request. |  
  |  
 
US & International                                             Standard Support hours are                                             Monday - Friday 6AM - 6PM US Pacific                                             For 24/7 Urgent Support, please call:                                             1.866.KGI.SLOT                                                                                                                                                                Australia                                             Standard Support hours are                                             Monday - Friday 9AM - 5PM Australian Eastern                                             For 24/7 Urgent Support, please call:                                             1300.800.844 |   | US & International                                             Standard Support hours are                                             Monday - Friday 6AM - 6PM US Pacific                                             For 24/7 Urgent Support, please call:                                             1.866.KGI.SLOT | Australia                                             Standard Support hours are                                             Monday - Friday 9AM - 5PM Australian Eastern                                             For 24/7 Urgent Support, please call:                                             1300.800.844 |  
  | US & International                                             Standard Support hours are                                             Monday - Friday 6AM - 6PM US Pacific                                             For 24/7 Urgent Support, please call:                                             1.866.KGI.SLOT | Australia                                             Standard Support hours are                                             Monday - Friday 9AM - 5PM Australian Eastern                                             For 24/7 Urgent Support, please call:                                             1300.800.844 |  
  |  
 
Thank you,                                                                                           Konami Gaming, Inc. Customer Service |   | Thank you,                                                                                           Konami Gaming, Inc. Customer Service
  | Thank you,                                                                                           Konami Gaming, Inc. Customer Service
www.gaming.konami.com \| 1.866.KGI.SLOT |   | www.gaming.konami.com \| 1.866.KGI.SLOT
  | www.gaming.konami.com \| 1.866.KGI.SLOT

**Comment by richelbilderbeek** [comment]
@rijkvp:

> And why Twich? Didn't you mean Itch.io?

Yes, I meant itch.io :rainbow:

**Comment by rijkvp** [comment]
I exported the game. The windows export includes the JRE but on linux you need to have a JRE installed.

**Downloads:**
[Windows 64bit](https://drive.google.com/file/d/15mamrIVURvDZWZ9cmPaCihfxW2cZGMN7)
[Linux 64bit](https://drive.google.com/file/d/1iA8HHxbwiic3z7kysODHYwkHkqVHDSZg)

You have to unzip the archive and run the executable `tank_battalion`.

@richelbilderbeek, can you check if the build works on Linux?

I will export an updated version if @robkruger finishes #83 .

We can upload it to Itch.io if we get a response email

**Comment by richelbilderbeek** [comment]
Great job! I just checked on Ubuntu:

```
richel@N141CU:~/Downloads/Tank-Battalion_Linux64$ ./tank_battalion 
The font "../assets/fonts/RetroGaming.ttf" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
Sound library error: unable to find file ../assets/audio/start_music.wav
java.lang.NullPointerException
	at processing.sound.AudioSample.frames(Unknown Source)
	at processing.sound.SoundFile.frames(Unknown Source)
	at processing.sound.AudioSample.playInternal(Unknown Source)
	at processing.sound.AudioSample.play(Unknown Source)
	at processing.sound.SoundFile.play(Unknown Source)
	at tank_battalion$AudioManager.play_sound(tank_battalion.java:101)
	at tank_battalion$MenuState.on_start(tank_battalion.java:1562)
	at tank_battalion$StateManager.<init>(tank_battalion.java:1972)
	at tank_battalion.setup(tank_battalion.java:68)
	at processing.core.PApplet.handleDraw(PApplet.java:2432)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
```

Seems like an easy fix to me :+1:

**Comment by rijkvp** [comment]
😂 I forgot to copy the assets for the Linux build

**Comment by richelbilderbeek** [comment]
@rijkvp want me to check again?

**Comment by rijkvp** [comment]
> @rijkvp want me to check again?

@richelbilderbeek , yes, I have updated the link in my previous comment.

**Comment by richelbilderbeek** [comment]
@rijkvp I just checked: it works perfectly!
