### ISSUE TITLE
Install processing & clone the repo

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2020#9]
Dutch GitHub help: [djog.github.io/help](https://djog.github.io/help/)
Unassign yourself if you're done.

**Comment by antonhensen81** [comment]
Removing Joshua from this issue as he move to the other project. Also, @AramPetiet I suspect you've done this and we can move the issue to done?

**Comment by antonhensen81** [comment]
Oh, it seems I cannot remove assignees. @Joshua260403 can you remove yourself from the 'assignees'?

**Comment by rijkvp** [comment]
Done!
